### PR TITLE
feature: TRACEFOSS-1439 add test scope to dash IP license check

### PR DESCRIPTION
**Pull request by ds-lcapellino**

### CODE REVIEW

**Review by ds-ext-sceronik — APPROVED** [review]
LGTM

**Review by ds-mwesener — CHANGES_REQUESTED** [review]
Please add a changelog

**Review by ds-mwesener — CHANGES_REQUESTED** [review]
Please also check frontend. Thanks

**Comment by ds-lcapellino** [comment]
> Please also check frontend. Thanks

All frontend dependencies should already be inside DEPENDENCIES_FRONTEND file.

**Review by ds-mwesener — APPROVED** [review]

**Pull request merged**
