### PR TITLE
TRACEFOSS-1278 setup testdata and provide documentation

### PR DESCRIPTION
**Pull request by ds-mmaul**
See [TRACEFOSS-1278](https://jira.catena-x.net/browse/TRACEFOSS-1278)

### CODE REVIEW

**Review by mkanal — DISMISSED** [review]
Why do we duplicate this testdata here in Trace-X are there any modification to those in IRS? If not a link to IRS repository wil be enough.

**Review by mkanal — COMMENTED** [review]
Do duplication of testdata to donot run out of sync or is there currently a need to adjust the IRS testfiles?

**Review by mkanal — COMMENTED** [review]
Do duplication of testdata to donot run out of sync or is there currently a need to adjust the IRS testfiles?

**Review by mkanal — COMMENTED** [review]
Do duplication of testdata to donot run out of sync or is there currently a need to adjust the IRS testfiles?

**Review by ds-mwesener — APPROVED** [review]
LGTM

**Pull request merged**
