### PR TITLE
fix: TRACEFOSS-1460 Repaired unit tests and dependencies

### PR DESCRIPTION
**Pull request by ds-ext-dskrzypczak**
…kit/build-angular" to 15.2.3

### CODE REVIEW

**Review by ds-mwesener — CHANGES_REQUESTED** [review]
Hi Darek the webpack version you downgrade to has a high vulnerability. Please find another solution or mitigate it.

**Comment by ds-ext-dskrzypczak** [comment]
> Hi Darek the webpack version you downgrade to has a high vulnerability. Please find another solution or mitigate it.

@ds-mwesener Did you mean this one?
https://github.com/advisories/GHSA-hc6q-2mpp-qw7j

**Comment by ds-mwesener** [comment]
> > Hi Darek the webpack version you downgrade to has a high vulnerability. Please find another solution or mitigate it.
> 
> @ds-mwesener Did you mean this one? [GHSA-hc6q-2mpp-qw7j](https://github.com/advisories/GHSA-hc6q-2mpp-qw7j)
Yes

**Review by ds-mwesener — CHANGES_REQUESTED** [review]
Hi, please make sure to merge main into your branch. You are a lot of commits behind, just to make sure there are no problems. Thanks

**Comment by ds-mwesener** [comment]
> [**TX Traceability FOSS frontend**] Kudos, SonarCloud Quality Gate passed!    [Quality Gate passed](https://sonarcloud.io/dashboard?id=catenax-ng_tx-traceability-foss_frontend&pullRequest=241)
> 
> [Bug](https://sonarcloud.io/project/issues?id=catenax-ng_tx-traceability-foss_frontend&pullRequest=241&resolved=false&types=BUG) [A](https://sonarcloud.io/project/issues?id=catenax-ng_tx-traceability-foss_frontend&pullRequest=241&resolved=false&types=BUG) [0 Bugs](https://sonarcloud.io/project/issues?id=catenax-ng_tx-traceability-foss_frontend&pullRequest=241&resolved=false&types=BUG) [Vulnerability](https://sonarcloud.io/project/issues?id=catenax-ng_tx-traceability-foss_frontend&pullRequest=241&resolved=false&types=VULNERABILITY) [A](https://sonarcloud.io/project/issues?id=catenax-ng_tx-traceability-foss_frontend&pullRequest=241&resolved=false&types=VULNERABILITY) [0 Vulnerabilities](https://sonarcloud.io/project/issues?id=catenax-ng_tx-traceability-foss_frontend&pullRequest=241&resolved=false&types=VULNERABILITY) [Security Hotspot](https://sonarcloud.io/project/security_hotspots?id=catenax-ng_tx-traceability-foss_frontend&pullRequest=241&resolved=false&types=SECURITY_HOTSPOT) [A](https://sonarcloud.io/project/security_hotspots?id=catenax-ng_tx-traceability-foss_frontend&pullRequest=241&resolved=false&types=SECURITY_HOTSPOT) [0 Security Hotspots](https://sonarcloud.io/project/security_hotspots?id=catenax-ng_tx-traceability-foss_frontend&pullRequest=241&resolved=false&types=SECURITY_HOTSPOT) [Code Smell](https://sonarcloud.io/project/issues?id=catenax-ng_tx-traceability-foss_frontend&pullRequest=241&resolved=false&types=CODE_SMELL) [A](https://sonarcloud.io/project/issues?id=catenax-ng_tx-traceability-foss_frontend&pullRequest=241&resolved=false&types=CODE_SMELL) [7 Code Smells](https://sonarcloud.io/project/issues?id=catenax-ng_tx-traceability-foss_frontend&pullRequest=241&resolved=false&types=CODE_SMELL)
> 
> [](https://sonarcloud.io/component_measures?id=catenax-ng_tx-traceability-foss_frontend&pullRequest=241&metric=new_coverage&view=list) [83.1% Coverage](https://sonarcloud.io/component_measures?id=catenax-ng_tx-traceability-foss_frontend&pullRequest=241&metric=new_coverage&view=list) [](https://sonarcloud.io/component_measures?id=catenax-ng_tx-traceability-foss_frontend&pullRequest=241&metric=new_duplicated_lines_density&view=list) [0.0% Duplication](https://sonarcloud.io/component_measures?id=catenax-ng_tx-traceability-foss_frontend&pullRequest=241&metric=new_duplicated_lines_density&view=list)

@ds-ext-dskrzypczak please fix code smells

**Comment by ds-mwesener** [comment]
Hi, this high vulnerability is still there: https://github.com/catenax-ng/tx-traceability-foss/security/dependabot/11

**Comment by ds-mwesener** [comment]
Please also execute the generation of the DEPENDENCIES_FRONTEND file

**Comment by ds-ext-dskrzypczak** [comment]
> Hi, this high vulnerability is still there: [engine.io Uncaught Exception vulnerability](/catenax-ng/tx-traceability-foss/security/dependabot/11)

Yes, but this is not a part of the current topic. It will be solved in [TRACEFOSS-1459].

**Comment by ds-ext-dskrzypczak** [comment]
> Hi, please make sure to merge main into your branch. You are a lot of commits behind, just to make sure there are no problems. Thanks

Done. There was nothing related with FE, but thanks anyway for the hint.

**Comment by ds-ext-dskrzypczak** [comment]
> DEPENDENCIES_FRONTEND

Done.

**Comment by ds-ext-dskrzypczak** [comment]
> Hi, this high vulnerability is still there: [engine.io Uncaught Exception vulnerability](/catenax-ng/tx-traceability-foss/security/dependabot/11)

Ok, finally I manage to fix that in this PR:
https://github.com/catenax-ng/tx-traceability-foss/pull/241/commits/4dc19676e55d2ae3de3225a211d5143afd592adb

**Comment by ds-ext-dskrzypczak** [comment]
> > [**TX Traceability FOSS frontend**] Kudos, SonarCloud Quality Gate passed!    [Quality Gate passed](https://sonarcloud.io/dashboard?id=catenax-ng_tx-traceability-foss_frontend&pullRequest=241)
> > [Bug](https://sonarcloud.io/project/issues?id=catenax-ng_tx-traceability-foss_frontend&pullRequest=241&resolved=false&types=BUG) [A](https://sonarcloud.io/project/issues?id=catenax-ng_tx-traceability-foss_frontend&pullRequest=241&resolved=false&types=BUG) [0 Bugs](https://sonarcloud.io/project/issues?id=catenax-ng_tx-traceability-foss_frontend&pullRequest=241&resolved=false&types=BUG) [Vulnerability](https://sonarcloud.io/project/issues?id=catenax-ng_tx-traceability-foss_frontend&pullRequest=241&resolved=false&types=VULNERABILITY) [A](https://sonarcloud.io/project/issues?id=catenax-ng_tx-traceability-foss_frontend&pullRequest=241&resolved=false&types=VULNERABILITY) [0 Vulnerabilities](https://sonarcloud.io/project/issues?id=catenax-ng_tx-traceability-foss_frontend&pullRequest=241&resolved=false&types=VULNERABILITY) [Security Hotspot](https://sonarcloud.io/project/security_hotspots?id=catenax-ng_tx-traceability-foss_frontend&pullRequest=241&resolved=false&types=SECURITY_HOTSPOT) [A](https://sonarcloud.io/project/security_hotspots?id=catenax-ng_tx-traceability-foss_frontend&pullRequest=241&resolved=false&types=SECURITY_HOTSPOT) [0 Security Hotspots](https://sonarcloud.io/project/security_hotspots?id=catenax-ng_tx-traceability-foss_frontend&pullRequest=241&resolved=false&types=SECURITY_HOTSPOT) [Code Smell](https://sonarcloud.io/project/issues?id=catenax-ng_tx-traceability-foss_frontend&pullRequest=241&resolved=false&types=CODE_SMELL) [A](https://sonarcloud.io/project/issues?id=catenax-ng_tx-traceability-foss_frontend&pullRequest=241&resolved=false&types=CODE_SMELL) [7 Code Smells](https://sonarcloud.io/project/issues?id=catenax-ng_tx-traceability-foss_frontend&pullRequest=241&resolved=false&types=CODE_SMELL)
> > [](https://sonarcloud.io/component_measures?id=catenax-ng_tx-traceability-foss_frontend&pullRequest=241&metric=new_coverage&view=list) [83.1% Coverage](https://sonarcloud.io/component_measures?id=catenax-ng_tx-traceability-foss_frontend&pullRequest=241&metric=new_coverage&view=list) [](https://sonarcloud.io/component_measures?id=catenax-ng_tx-traceability-foss_frontend&pullRequest=241&metric=new_duplicated_lines_density&view=list) [0.0% Duplication](https://sonarcloud.io/component_measures?id=catenax-ng_tx-traceability-foss_frontend&pullRequest=241&metric=new_duplicated_lines_density&view=list)
> 
> @ds-ext-dskrzypczak please fix code smells

Done. 

Created task TRACEFOSS-1476 for refactoring AuthGuard (one of TODOs)

**Review by ds-mwesener — APPROVED** [review]
LGTM

**Pull request merged**
