### PR TITLE
Feature/tracefoss 2668 be allow sorting on notifications

### PR DESCRIPTION
**Pull request by ds-ext-sceronik**
Had to add @Enumerated(EnumType.STRING) and change database field type from int to varchar

### CODE REVIEW

**Review by ds-lcapellino — CHANGES_REQUESTED** [review]
Update CHANGELOG.md please :)

**Comment by ds-ext-sceronik** [comment]
> Update CHANGELOG.md please :)

updated ! :) thanks <3

**Comment by ds-ext-sceronik** [comment]
since local integration tests were passing and environment were failing I have changed integration tests to use flyway. that way we will reduce situation when integration tests are running and environment deployment is failing due to different way of creating database schema

**Review by ds-lcapellino — APPROVED** [review]
LGTM!

**Pull request merged**
